#!/usr/bin/env python3
"""Run self-correction diagnostics for the material-feedback model."""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from utility_endogenous.self_correction import run_self_correction_analysis


def fmt(value: object) -> str:
    if isinstance(value, float):
        if value != value:
            return ""
        return f"{value:.6g}"
    return str(value)


def markdown_table(rows: list[dict[str, object]], columns: list[str], labels: dict[str, str] | None = None) -> str:
    labels = labels or {}
    header = "| " + " | ".join(labels.get(column, column) for column in columns) + " |"
    separator = "| " + " | ".join(["---"] * len(columns)) + " |"
    body = [
        "| " + " | ".join(fmt(row.get(column, "")) for column in columns) + " |"
        for row in rows
    ]
    return "\n".join([header, separator, *body])


def write_report(output: dict[str, object]) -> None:
    signal_rows = [asdict(row) for row in output["signal_rows"]]
    stock_summary = [asdict(row) for row in output["stock_summary"]]
    competition_summary = [asdict(row) for row in output["competition_summary"]]
    sampled_stock = [
        row
        for row in stock_summary
        if abs((float(row["capacity_protection"]) * 2.0) - round(float(row["capacity_protection"]) * 2.0)) < 1e-9
    ]
    report = "\n".join(
        [
            "# Self-Correction Diagnostics",
            "",
            "Generated by `python3 scripts/run_self_correction_analysis.py`.",
            "",
            "## Main Readout",
            "",
            "A material-reality signal does not automatically repair an induced-preference",
            "loop. If the signal is only the current capacity drift, then the roots of",
            "the reduced capacity equation are unchanged: at any steady state the drift",
            "signal is zero. It can damp motion, but it does not eliminate the trap.",
            "",
            f"In the baseline trap calibration, the maximum numerical root displacement",
            f"from drift-signal feedback is `{float(output['max_signal_root_error']):.3e}`.",
            "",
            "In this diagnostic, the tested current-drift signal does not remove",
            "the low-capacity trap. The displayed stock-channel sweep, here through",
            "the capacity-protection parameter `rho`, can remove it. In the same",
            "calibration, the low-capacity trap disappears once `rho` is about",
            f"`{float(output['first_self_correcting_rho']):.2f}` on the grid used here.",
            "",
            "Competition adds a Darwinian layer. It does not rewrite an individual",
            "rule's capacity dynamics. It reallocates population share, capital,",
            "attention, or institutional prevalence toward rules that score higher",
            "on the operative competitive score `S`. Absolute material survival is",
            "tracked separately by material growth `g`. With material-viability",
            "competition, `S` is aligned with `g` and the capacity-building rule",
            "wins. With engagement-proxy competition, the capacity-draining rule",
            "can win while material population mass falls.",
            "",
            "## Drift-Signal Equilibria",
            "",
            markdown_table(
                signal_rows,
                [
                    "signal_strength",
                    "capacity",
                    "substitute_share",
                    "drift_slope",
                    "stable",
                    "root_error_vs_no_signal",
                ],
            ),
            "",
            "## Stock-Feedback Summary",
            "",
            markdown_table(
                sampled_stock,
                [
                    "capacity_protection",
                    "stable_count",
                    "low_trap_present",
                    "threshold_present",
                    "high_state_present",
                ],
            ),
            "",
            "## Competition Summary",
            "",
            markdown_table(
                competition_summary,
                [
                    "selection_metric",
                    "competition_intensity",
                    "final_bridge_share",
                    "final_bridge_capacity",
                    "final_sink_capacity",
                    "final_population_mass",
                    "final_mean_material_growth",
                    "verdict",
                ],
                {
                    "selection_metric": "competitive score",
                    "competition_intensity": "competition omega",
                    "final_bridge_share": "final building-rule share",
                    "final_bridge_capacity": "final building-rule capacity",
                    "final_sink_capacity": "final draining-rule capacity",
                    "final_population_mass": "final material scale",
                    "final_mean_material_growth": "final material growth",
                    "verdict": "readout",
                },
            ),
            "",
            "## Interpretation",
            "",
            "- Current pain or deteriorating-flow reports are not enough if",
            "  they vanish once the system settles into a low-capacity state.",
            "- In this diagnostic, automatic correction comes from a persistent",
            "  material state channel, or from competition when the competitive score",
            "  is aligned with material viability.",
            "- This is a Nash/Darwin result rather than advice: the subjective Nash map",
            "  produces behavior, behavior moves capacity, and selection can only favor",
            "  fitter rules if the material evaluator actually governs reproduction,",
            "  survival, exit, imitation, or institutional persistence.",
            "- If competition is over a proxy such as engagement, the Darwinian operator",
            "  is still active, but it selects the rule that wins the proxy contest.",
            "  Relative victory under `S` and material survival under `g` are different",
            "  claims.",
            "",
            "## Generated Artifacts",
            "",
            "Tables:",
            "",
            *[f"- `{path}`" for path in output["tables"]],
            "",
            "Figures:",
            "",
            *[f"- `{path}`" for path in output["figures"]],
            "",
        ]
    )
    (ROOT / "results" / "self_correction_report.md").write_text(report, encoding="utf-8")


def main() -> None:
    output = run_self_correction_analysis(ROOT)
    write_report(output)
    print("Wrote self-correction diagnostics.")
    print(ROOT / "results" / "self_correction_report.md")


if __name__ == "__main__":
    main()
