#!/usr/bin/env python3
"""Run bootstrap simulations for the endogenous utility project."""

from __future__ import annotations

import csv
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from utility_endogenous.endogenous_taste import simulate_taste_drift, taste_scenarios
from utility_endogenous.indirect_evolution import (
    simulate_social_preferences,
    social_preference_scenarios,
)


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise ValueError(f"No rows to write for {path}")
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def last_by_scenario(rows: list[dict[str, object]]) -> list[dict[str, object]]:
    latest: dict[str, dict[str, object]] = {}
    for row in rows:
        latest[str(row["scenario"])] = row
    return list(latest.values())


def fmt(value: object, digits: int = 4) -> str:
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def markdown_table(rows: list[dict[str, object]], columns: list[str]) -> str:
    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join(["---"] * len(columns)) + " |"
    body = [
        "| " + " | ".join(fmt(row[column]) for column in columns) + " |"
        for row in rows
    ]
    return "\n".join([header, separator, *body])


def scenario_deltas(rows: list[dict[str, object]], key: str) -> dict[str, float]:
    first: dict[str, float] = {}
    last: dict[str, float] = {}
    for row in rows:
        scenario = str(row["scenario"])
        value = float(row[key])
        first.setdefault(scenario, value)
        last[scenario] = value
    return {scenario: last[scenario] - first[scenario] for scenario in last}


def build_report(
    taste_rows: list[dict[str, object]],
    social_rows: list[dict[str, object]],
) -> str:
    taste_final = last_by_scenario(taste_rows)
    social_final = last_by_scenario(social_rows)
    taste_delta_theta = scenario_deltas(taste_rows, "mean_theta")
    taste_delta_fitness = scenario_deltas(taste_rows, "mean_fitness")
    social_delta_q = scenario_deltas(social_rows, "cooperation_rate")

    lines = [
        "# Toy Model Report",
        "",
        "Generated by `python3 scripts/run_toy_models.py`.",
        "",
        "## Algorithmic Taste Drift",
        "",
        markdown_table(
            taste_final,
            [
                "scenario",
                "period",
                "mean_theta",
                "attention_share",
                "offline_social_capital",
                "mean_fitness",
                "subjective_satisfaction",
                "entropy",
            ],
        ),
        "",
        "### Taste Drift Deltas",
        "",
        markdown_table(
            [
                {
                    "scenario": scenario,
                    "delta_mean_theta": taste_delta_theta[scenario],
                    "delta_mean_fitness": taste_delta_fitness[scenario],
                }
                for scenario in taste_delta_theta
            ],
            ["scenario", "delta_mean_theta", "delta_mean_fitness"],
        ),
        "",
        "Interpretation: `mean_theta` is online/artificial taste orientation. `mean_fitness` is a separate biological/social fitness proxy. The interesting case is a positive taste drift with a negative fitness drift.",
        "",
        "## Indirect Evolutionary Prisoner's Dilemma",
        "",
        markdown_table(
            social_final,
            [
                "scenario",
                "period",
                "mean_lambda",
                "cooperation_rate",
                "mean_material_payoff",
                "mean_subjective_value",
            ],
        ),
        "",
        "### Cooperation Deltas",
        "",
        markdown_table(
            [
                {
                    "scenario": scenario,
                    "delta_cooperation_rate": social_delta_q[scenario],
                }
                for scenario in social_delta_q
            ],
            ["scenario", "delta_cooperation_rate"],
        ),
        "",
        "Interpretation: `lambda` is the social-preference parameter. Positive institutional preference drift can stabilize cooperation; conflict-oriented preference drift can collapse it.",
        "",
        "## Bootstrap Conclusions",
        "",
        "1. The endogenous-preference state changes the object of equilibrium: the transition law matters as much as the current best response.",
        "2. In the algorithmic-capture scenario, the toy model permits subjective satisfaction to remain high while social fitness deteriorates.",
        "3. In the evolutionary game, selection alone and preference mutation can point in opposite directions; institutions choose which preference basin the economy visits.",
        "4. The next step is to endogenize the platform policy rather than treating the algorithmic field as a parameter.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    results_dir = ROOT / "results"
    tables_dir = results_dir / "tables"

    taste_rows: list[dict[str, object]] = []
    for scenario in taste_scenarios():
        taste_rows.extend(simulate_taste_drift(scenario))

    social_rows: list[dict[str, object]] = []
    for scenario in social_preference_scenarios():
        social_rows.extend(simulate_social_preferences(scenario))

    write_csv(tables_dir / "endogenous_taste_summary.csv", taste_rows)
    write_csv(tables_dir / "indirect_evolution_summary.csv", social_rows)
    (results_dir / "toy_model_report.md").write_text(
        build_report(taste_rows, social_rows),
        encoding="utf-8",
    )

    print(f"Wrote {tables_dir / 'endogenous_taste_summary.csv'}")
    print(f"Wrote {tables_dir / 'indirect_evolution_summary.csv'}")
    print(f"Wrote {results_dir / 'toy_model_report.md'}")


if __name__ == "__main__":
    main()
