#!/usr/bin/env python3
"""Run the fashion, influencer, and meme preference-closure analysis."""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from utility_endogenous.fashion_meme_dynamics import run_fashion_meme_analysis


def fmt(value: object) -> str:
    if isinstance(value, float):
        return f"{value:.4f}"
    return str(value)


def markdown_table(rows: list[dict[str, object]], columns: list[str]) -> str:
    header = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join(["---"] * len(columns)) + " |"
    body = [
        "| " + " | ".join(fmt(row.get(column, "")) for column in columns) + " |"
        for row in rows
    ]
    return "\n".join([header, sep, *body])


def write_report(output: dict[str, object]) -> None:
    threshold = output["threshold"]
    network_rows = output["network_rows"]
    audit = output["audit"]

    threshold_row = asdict(threshold)
    network_sample = [asdict(row) for row in network_rows][-4:]
    audit_row = asdict(audit)

    report = "\n".join(
        [
            "# Fashion, Influencer, And Meme Closure Results",
            "",
            "Generated by `python3 scripts/run_fashion_meme_analysis.py`.",
            "",
            "## Main Finding",
            "",
            "A fashion or meme field is harmlessly continuous only below a critical",
            "social-feedback threshold. Above that threshold, preference closure can",
            "be multi-valued: a temporary influencer or meme shock can move the",
            "economy from one stable taste state to another, and the new state can",
            "persist after the shock disappears.",
            "",
            "## Mean-Field Threshold",
            "",
            markdown_table(
                [threshold_row],
                [
                    "beta",
                    "social_feedback",
                    "material_field",
                    "beta_j",
                    "critical_field",
                    "positive_shock_needed",
                    "shock_size",
                    "persistent_flip",
                    "material_loss_if_material_field_negative",
                ],
            ),
            "",
            "## Network Influence Multipliers",
            "",
            markdown_table(
                network_sample,
                [
                    "eta",
                    "beta_eta_rho",
                    "central_response",
                    "peripheral_response",
                    "central_to_peripheral_ratio",
                    "contraction_bound",
                ],
            ),
            "",
            "## Random Parameter Audit",
            "",
            markdown_table(
                [audit_row],
                [
                    "draws",
                    "shock_size",
                    "subcritical_unique_rate",
                    "hysteresis_possible_rate",
                    "temporary_shock_flip_rate",
                    "material_loss_flip_rate",
                    "mean_positive_shock_needed_when_flippable",
                    "median_positive_shock_needed_when_flippable",
                ],
            ),
            "",
            "## Generated Artifacts",
            "",
            "Tables:",
            "",
            *[f"- `{path}`" for path in output["tables"]],
            "",
            "Figures:",
            "",
            *[f"- `{path}`" for path in output["figures"]],
            "",
        ]
    )
    (ROOT / "results" / "fashion_meme_report.md").write_text(report, encoding="utf-8")


def main() -> None:
    output = run_fashion_meme_analysis(ROOT)
    write_report(output)
    print("Wrote fashion meme analysis outputs.")
    print(ROOT / "results" / "fashion_meme_report.md")


if __name__ == "__main__":
    main()
