#!/usr/bin/env python3
"""Run the material-capacity feedback analysis."""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from utility_endogenous.material_feedback import run_material_feedback_analysis


def fmt(value: object) -> str:
    if isinstance(value, float):
        if value != value:
            return ""
        return f"{value:.4f}"
    return str(value)


def markdown_table(rows: list[dict[str, object]], columns: list[str]) -> str:
    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join(["---"] * len(columns)) + " |"
    body = [
        "| " + " | ".join(fmt(row.get(column, "")) for column in columns) + " |"
        for row in rows
    ]
    return "\n".join([header, separator, *body])


def write_report(output: dict[str, object]) -> None:
    equilibria = output["equilibria"]
    audit = [asdict(row) for row in output["audit"]]
    audit_design = [
        {
            "feedback_class": label,
            "L_range": f"[{damage_low:.2f}, {damage_high:.2f}]",
            "beta_range": f"[{beta_low:.1f}, {beta_high:.1f}]",
            "rho_range": f"[{rho_low:.2f}, {rho_high:.2f}]",
            "shared_ranges": "alpha in [0.10,0.28], r in [1,4], d in [0.22,0.78], q in [0.35,0.65], z in [-0.05,0.10]",
        }
        for label, damage_low, damage_high, beta_low, beta_high, rho_low, rho_high
        in output["audit_classes"]
    ]

    report = "\n".join(
        [
            "# Material Feedback Results",
            "",
            "Generated by `python3 scripts/run_material_feedback_analysis.py`.",
            "",
            "## Model",
            "",
            "The fast subsystem maps material capacity `K` into the subjective",
            "attractiveness of a substitute behavior:",
            "",
            "```text",
            "p(K) = logistic(beta * (q + z - rho K))",
            "```",
            "",
            "The slow capacity stock then evolves as:",
            "",
            "```text",
            "Kdot = alpha + r K^2 (1 - K) - d K - L p(K)",
            "```",
            "",
            "The term `alpha + r K^2(1-K)` represents baseline and practice-based",
            "repair, `dK` is maintenance decay, and `L p(K)` is damage or crowding",
            "out from the substitute behavior. Capacity is projected onto `[0,1]`:",
            "if the unprojected drift points below zero or above one, the boundary",
            "is treated as a feasible boundary state. This is a stylized normal",
            "form, not an empirical estimate.",
            "",
            "## Main Finding",
            "",
            "In the self-correcting calibration, weak feedback has one stable",
            "high-capacity state. In the capacity-trap calibration, the same model",
            "has two stable states separated by an unstable threshold. In the random audit, weak feedback",
            "is mostly single-state, trap-prone feedback has the highest rate of",
            "low-high traps, and collapse-prone feedback more often reaches the",
            "lower boundary of the projected capacity interval.",
            "",
            "The main-text regime map varies baseline repair `alpha` and substitute",
            "damage `L` while holding the remaining trap-calibration parameters fixed.",
            "The baseline point lies in the threshold-trap region. Moving upward",
            "raises repair; moving left lowers damage per substitute use. These",
            "movements can cross into the capacity-building region, while weaker repair and",
            "higher damage move the system toward collapse-prone dynamics.",
            "",
            "## Baseline Equilibria",
            "",
            markdown_table(
                equilibria,
                ["scenario", "capacity", "substitute_share", "drift_slope", "stable"],
            ),
            "",
            "## Parameter Audit",
            "",
            markdown_table(
                audit,
                [
                    "feedback_class",
                    "draws",
                    "one_stable_state_rate",
                    "multiple_stable_states_rate",
                    "no_interior_stable_state_rate",
                    "lower_boundary_state_rate",
                    "low_high_trap_rate",
                    "mean_trap_threshold_when_present",
                    "median_trap_threshold_when_present",
                ],
            ),
            "",
            "## Audit Design",
            "",
            "The audit uses seed `20260626` and `3,000` draws per feedback class.",
            "Classes differ only in damage `L`, sensitivity `beta`, and capacity",
            "protection `rho`; the remaining parameter ranges are shared.",
            "",
            markdown_table(
                audit_design,
                ["feedback_class", "L_range", "beta_range", "rho_range", "shared_ranges"],
            ),
            "",
            "## Interpretation",
            "",
            "- A fixed-preference model can describe choice once the payoff criterion is",
            "  formed, but it misses whether today's choice changes tomorrow's",
            "  capacity and therefore tomorrow's payoff criterion.",
            "- Nash equilibrium remains the consistency condition inside the induced",
            "  subjective game; it does not certify the feedback loop that produced",
            "  the subjective payoffs.",
            "- Darwinian or selection language becomes operational only after naming the",
            "  capacity stock: solvency, health, fertility capacity, friendship skill,",
            "  learning, trust, institutional competence, or demographic continuity.",
            "- The same formal loop covers harms and repairs. A platform can raise",
            "  `z`, `beta`, or `L`; a therapeutic, educational, or AI-assistant design",
            "  can lower those terms or raise repair.",
            "",
            "## Generated Artifacts",
            "",
            "Tables:",
            "",
            *[f"- `{path}`" for path in output["tables"]],
            "",
            "Figures:",
            "",
            *[f"- `{path}`" for path in output["figures"]],
            "",
        ]
    )
    (ROOT / "results" / "material_feedback_report.md").write_text(report, encoding="utf-8")


def main() -> None:
    output = run_material_feedback_analysis(ROOT)
    write_report(output)
    print("Wrote material feedback analysis outputs.")
    print(ROOT / "results" / "material_feedback_report.md")


if __name__ == "__main__":
    main()
